title: James Louis # your name (or website title) here
logo: "/images/Screenshot_20201112-211215.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A recent Computer Science graduate who is changing careers from healthcare to software engineering! 
  After being a Respiratory Therapist for ten years I realized that my job felt mundane, I no longer felt challenged or excited for my job. I decided I wanted to change careers and do something
  that challenges me. Software engineering has been the answer. I never coded anything so learning langauges and platforms proved to be a challenge. As challenging as it has been, I have 
  truly enjoyed it. I completed my online degree from Southern New Hampshire University. One thing I have taken away from online schooling is the dedication of learning and teaching yourself something
  is truly valuable.
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
